const uniteAdministrative = [
  {
    name: "Alibori",
    communes: [
      {
        nom: "Banikoara",
        arrondissement: [
          {
            nom: "Banikoara",
            villes: [
              "Argonga",
              "Aviation",
              "Batran",
              "Demanou",
              "Derou Garou",
              "Glebabi",
              "Guiguiri",
              "kokire",
              "Kommon",
              "Kori Guiguiri",
              "Kpagaguedou",
              "Orou Gnonrou",
              "Samanga",
              "Tokey-Banta",
              "Wagou",
              "Weterou",
              "Yadikparou",
            ],
          },
          {
            nom: "Founougo",
            villes: [
              "Bofounou",
              "Founougo-Boutera",
              "Founougo-Gah",
              "Founougo-Gorobani",
              "Gama",
              "Gamere-Zongo",
              "Gougnirou",
              "Gougnirou-Gah",
              "Iboto",
              "Kanderou",
              "Kanderou-Kotchera",
              "Koney",
              "Kpako-Gbabi",
              "Pougoussorou",
              "Sampeto",
              "Sissianganrou",
              "Yangueri",
              "Yinyinpogou",
            ],
          },
          {
            nom: "Gomparou",
            villes: [
              "Bonhanrou",
              "Gnambarou",
              "Gomparou",
              "Gomparou-Goussinrou",
              "Gomparou-Gokpadou",
              "Goure-EDE",
              "Kali",
              "Kpessanrou",
              "Niekoubanta",
              "Pampime",
              "Sionkpekoka",
              "Tiganson",
              "Yossinande",
            ],
          },
          {
            nom: "Goumori",
            villes: [
              "Bonni",
              "Bonte",
              "Domboure",
              "Domboure-Gah",
              "Dondagou",
              "Gbangbanga",
              "Gbassa",
              "Goumori-Bayedou",
              "Goumori-Gah",
              "Goumori-Gbissarou",
              "Mondoukoka",
              "Mondoukoka-Gah",
              "Sakassinnou",
              "Satouba",
              "Tihoure",
            ],
          },
          {
            nom: "Kokey",
            villes: [
              "Gamarou",
              "kokey-Filo",
              "kokey-Sinakparou",
              "Nimbere",
              "Piguire",
              "Sonwari",
              "Yamberou",
            ],
          },
          {
            nom: "Kokoborou",
            villes: [
              "Bonkere",
              "Guinningou-Gah",
              "Kokiboorou",
              "Sirikou",
              "Sounsoun",
            ],
          },
          {
            nom: "Ounet",
            villes: [
              "Boniki",
              "Kihouhou",
              "Ounet-Gah",
              "Ounet-Sekogbaourou",
              "Ounet-Sinakparou",
              "Sonnou",
              "Sonnou-Gah",
              "Kpeborogou",
            ],
          },
          {
            nom: "Somperekou",
            villes: [
              "Bonyangou",
              "Gnandarou",
              "kegamorou",
              "Poto",
              "Poto-Gah",
              "Simperou",
              "Simperou-Gah",
              "Somperekou-Gah",
              "Somperekou-Gbessara",
              "Somperekou-Yorounon",
              "Bourin",
            ],
          },
          {
            nom: "Soroko",
            villes: [
              "Gbeniki",
              "Mekrou",
              "Soroko",
              "Soroko Gah",
              "Soroko Yorounon",
              "Soudou",
            ],
          },
          {
            nom: "Toura",
            villes: [
              "Atebenou",
              "Gnambourankorou",
              "Guimbagou",
              "Kakourogou",
              "Siwougourou",
              "Tintinmou",
              "Tintinmou-Gah",
              "Toura-Gah",
              "Toura-Bio N'Worou",
              "Toura-Yokparou",
            ],
          },
        ],
      },
      {
        nom: "Segbana",
        arrondissement: [
          {
            nom: "Lougou",
            villes: [
              "lougou",
              "Niambara",
              "Sinwa",
              "Zonzi",
              "Boumoussou",
              "Gandoloukassa",
              "Gbasse",
              "Gbekakarou",
              "Guenelaga",
              "Kamanan",
            ],
          },
          {
            nom: "Segbana",
            villes: [
              "Batazi",
              "Fondo",
              "Gbessare",
              "Guene Kouzi",
              "Korowi",
              "Kpassana",
              "Kpassana",
              "Limafrani",
              "Mafouta-Wassare",
              "Piami",
              "Samtimbara",
            ],
          },
          {
            nom: "Sokotindji",
            villes: [
              "Bedafou",
              "Gbarana",
              "Morou",
              "Poela",
              "Serebani",
              "Serekibe",
              "Sokotindji",
              "TCHAKAMA",
            ],
          },
          {
            nom: "Libante",
            villes: [
              "Bobena",
              "Diapeou",
              "Goungbe",
              "Koute",
              "Lbante",
              "Saonzi",
            ],
          },
          {
            nom: "Liboussou",
            villes: [
              "Gbessaka",
              "Kambara",
              "Lete",
              "Liboussou",
              "Tounga-Issa",
              "Waranzi",
            ],
          },
        ],
      },
      {
        nom: "Gogounou",
        arrondissement: [
          {
            nom: "Bagou",
            villes: [
              "Badou",
              "Bagou-Sinkparou",
              "Bagou-Yagbo",
              "Banigoure",
              "Bepororo",
              "Bouyagourou",
              "Diadia",
              "GaraGoro",
              "Kali",
              "Kangnan",
              "Kassirou",
              "Kerou-Bagou",
              "Kpakaguere",
              "Nafarou",
              "Orou-Bedou",
              "Tiati",
              "Yankpannou",
            ],
          },
          {
            nom: "Gogounou",
            villes: [
              "Djinmele",
              "Ggogunou-Gbanin",
              "Gogounou-Nassabara",
              "Goubera",
              "Konsenin",
              "Ouere-Bani",
              " Ouere-Sonkerou",
              "Sonkorou",
              "Sorou",
            ],
          },
          {
            nom: "Gounarou",
            villes: [
              "Bantansoue",
              "Boro",
              "Borodarou",
              "Dagourou",
              "Diguisson",
              "Gounarou",
              "Lafiarou",
              "Pariki",
            ],
          },
          {
            nom: "Sori",
            villes: [
              "Dimdimnou",
              "Donwari",
              "Gamagou",
              "Gassou",
              "Gbemoussou",
              "Gnindarou",
              "Goure-Dantcha",
              "Kantakpara-Wokperou",
              "Kpigourou",
              "Ouessene-Worou",
              "Petit-Paris",
              "Sori-Boro Wanrou",
              "Sori-Kpankpanou",
              "Sori-Peulh",
              "Tawali",
              "Tchoupounga",
            ],
          },
          {
            nom: "Sougou-Kpan-Trossi",
            villes: [
              "Binga",
              "Dougoulaye",
              "Fanan",
              "Gando-Dari",
              "Gbessa",
              "Sougou-Gourou",
              "Sougou-Kpantrossi",
            ],
          },
          {
            nom: "Wara",
            villes: [
              "Dassari",
              "Dougou",
              "Kale",
              "Soukarou",
              "Wara",
              "Wara-Gah",
              "Wara-Gbidogo",
            ],
          },
        ],
      },
      {
        nom: "Kandi",
        arrondissement: [
          {
            nom: "Angaradebou",
            villes: [
              "Akoitchaou",
              "Angaradebou",
              "Dogban",
              "Fafa",
              "Fouet",
              "Kabagbede",
              "Kpalolo",
              "Sekale",
              "Sondo",
              "Soundou",
              "Tchoka",
              "Thuy",
              "Thya",
              "Alfakoara",
            ],
          },
          {
            nom: "Bensekou",
            villes: ["Bensekou", "Gogbede", "Koutakroukou"],
          },
          {
            nom: "Donwari",
            villes: [
              "Dinin",
              "Dinin Peulh",
              "Dodondawa Somoutere",
              "Donwari",
              "Donwari-Peulh",
              "Gambane",
              "Gando",
              "Gourou Peulh",
              "Kpessarou",
              "Mongo",
              "Mongo-Peulh",
              "Siderou",
              "Tissarou",
              "Touko",
            ],
          },
          {
            nom: "Kandi 1",
            villes: [
              "Damadi",
              "Dodopanin",
              "Gando-Kossikana",
              "Gansosso-Gbigba",
              "Gansosso-Yirousse",
              "Kadjere",
              "Keferi-Hinkante",
              "Keferi-SInte",
              "Pede",
            ],
          },

          {
            nom: "Kandi 2",
            villes: [
              "AL Barika",
              "Alekpare",
              "Banigourou",
              "Baobab",
              "Kossarou",
              "Madina",
              "Zerman-Koure",
            ],
          },
          {
            nom: "Kandi 3",
            villes: [
              "Bakpara",
              "Heboumey",
              "Kandi-Fo",
              "Kandi-Fo-Peilh",
              "Lafiarou",
              "Podo",
              "Sinikoussou-Beri",
            ],
          },
          {
            nom: "Kassakou",
            villes: [
              "Firi",
              "Gbokoukou",
              "Gogore",
              "Kassakou",
              "Pade",
              "Pade-Peulh",
              "Pegon",
            ],
          },
          {
            nom: "Saah",
            villes: ["Banikani", "Foure", "Lolo", "Saah"],
          },
          {
            nom: "Sam",
            villes: [
              "Bikongou",
              "Boderou",
              "Boderou-Peulh",
              "Gbindarou",
              "SakaToussa",
              "SAM",
              "SAM-Gokirou",
              "SAM-Peulh",
              "Tankongou",
              "Tankongou-Dagourou",
              "Teri",
              "Wonga",
            ],
          },
          {
            nom: "Sonsoro",
            villes: [
              "Alibori-Yankin",
              "Pedigui",
              "Sinawongourou",
              "Sonsoro",
              "Sonsoro-Peulh",
              "Sinawongourou-Peulh",
            ],
          },
        ],
      },
      {
        nom:'Karimama',
        arrondissement:[
          {
            nom: 'Birni Lafia',
            villes: [
              ""
            ]
          }
        ]
      }
    ],
  },
];
